### ISSUE TITLE
Status switch doesn't always appear

### ISSUE THREAD

**Issue by cherise-bryan** [AXeL-dev/distract-me-not#1]
When you open the page to turn the blocker on/off, the switch doesn't always appear. Usually, this only happens the first time you open it. If you click again, the switch MIGHT appear. If you open a new tab or window, the same problem occurs again.

**Comment by joebain** [comment]
I've also had this issue, sometimes the entire popup is blank, sometimes the title shows. As for the OP clicking again will often show everything, but not always.

Firefox 67.0.1, Windows 10

![firefox_2019-06-10_09-56-46](https://user-images.githubusercontent.com/178859/59184536-3abe8400-8b66-11e9-9434-4b35b0c25ffc.png)

**Comment by AXeL-dev** [comment]
@joebain Thanks for reporting, i'll try to check that this weekend

**Comment by AXeL-dev** [comment]
Bug confirmed on firefox **private mode** , it seems to be related to this https://bugzilla.mozilla.org/show_bug.cgi?id=1329304

**Comment by joebain** [comment]
Just to update, I don't have private mode on when I see this. I do have uBlock and some other plugins though, Annoyingly I'm not seeing the problem today, but I'll update again if I can give you any more info on how to reproduce.

**Comment by AXeL-dev** [comment]
@joebain okay, i'm waiting for your news x)

**Comment by AXeL-dev** [comment]
Seems to be fixed.
