### ISSUE TITLE
URL Decoder not allowing local DNS Names

### ISSUE THREAD

**Issue by OttScott** [AXeL-dev/distract-me-not#100]
I have a variety of locally hosted services on my network that I reach by local DNS names.  The existing Distract-Me-Not URL Decoder Regex is not allowing me to enter local DNS names (IE "HTTP://stablediffusion/") as it doesn't have a Top Level Domain ending.  DNS Names should resolve to even single words or end with a ".".  For examples, the following URLs are not currently allowed in DMN:
stablediffusion
http://stablediffusion
http://stablediffusion:32444
ftp://a.stablediffusion:32444/r/typo/*

A better Regex for URL names is ^(?:(?:https?|ftp):\/\/)?(?:\*\.)*([\w-]+\.)*[\w-]+(?::\d+)?(?:\/[^\s\/]*)*(?:\/)?$
This matches a large variety of URL formats to include local paths and ports, as well as optional sub-paths with wildcard support. Feel free to tweak it as necessary.

### Your environment

- version of the extension: 2.8.0
- which browser and its version: Edge 123.0.2420.97 (Official build) (64-bit)

### Steps to reproduce

Tell us how to reproduce this issue. Please provide a working demo.
Open DMN Settings
Select Whitelist
Attempt to add a local dns name URI, IE: http://stablediffusion:32444

### Expected behaviour

Tell us what should happen:
URL should be accepted

### Actual behaviour

Tell us what happens instead
Error Message "Url is not valid"

**Comment by AXeL-dev** [comment]
This was fixed on release `2.8.1`, i will close the issue, please re-open it in case you still reproduce it.
