### ISSUE TITLE
Can't display option tab normally

### ISSUE THREAD

**Issue by RealSubstantiality** [AXeL-dev/distract-me-not#101]
As is shown in the picture, when I click the icon of this extension, a thin window appears, with not enough space for anything. However, the extension works fine, as I can still be blocked from blacklist sites. I believe that this problem occurred just recently, or I wouldn't be able to set my blacklist. I tried refreshing Firefox and redownload the extension but it doesn't help.
![2024-07-12-000810](https://github.com/AXeL-dev/distract-me-not/assets/113764554/3ba13d7b-0c0e-4cc5-a385-080614293467)
This is when I clicked the icon and the tab should be showing.
![2024-07-12-000821](https://github.com/AXeL-dev/distract-me-not/assets/113764554/88b5627a-5e29-4787-aaea-7b3c7fb2b775)
This is when I opened the browser and did nothing.

- Extension version: 2.8.0
- Browser: Firefox 128.0

**Comment by alrashwa** [comment]
Yes, noticed the same exact thing today. 

Extension Version 2.8.0
Firefox version 128.0 (64-bit)

**Comment by AXeL-dev** [comment]
Thanks for the report, i'll try to check it out once i get some time.

**Comment by nicocesar** [comment]
@AXeL-dev   Is this related to the fact that there was a change in the root certificate?

"The root certificate used to verify add-ons and signed content has been renewed to avoid upcoming expiration."

https://www.mozilla.org/en-US/firefox/128.0/releasenotes/

**Comment by AXeL-dev** [comment]
> @AXeL-dev Is this related to the fact that there was a change in the root certificate?
> 
> "The root certificate used to verify add-ons and signed content has been renewed to avoid upcoming expiration."
> 
> https://www.mozilla.org/en-US/firefox/128.0/releasenotes/

@nicocesar It might be the case, i will try to rebuild the extension & see if that resolves the issue.

**Comment by nicocesar** [comment]
@AXeL-dev Any news on this?

**Comment by AXeL-dev** [comment]
Sorry i didn't find time yet to check it out. I'm working full time on other projects therefore any help or pull requests are welcome.

**Comment by elburro1887** [comment]
Same issue here with version 2.80 on Firefox 128.0 on Mac OS 12.7.4

I've noticed that sometimes the settings popup menu opens when you quickly click the icon multiple times.

Also, if you right click on the icon and go to "Manage Extension", you can then click on the "..." menu and open "Preferences" and set them there, for now.

So in the end I'm not sure if this would be related to some expired certificate, but this is just an assumption...

**Comment by pycoder08** [comment]
@elburro1887 You're a lifesaver, thanks

**Comment by AXeL-dev** [comment]
Should be fixed on release `2.8.1`, i will close the issue, please re-open it in case you still reproduce it.

**Comment by nicocesar** [comment]
I can confirm this work for me like a charm @AXeL-dev !

Thank you for your time to fix it.
