### ISSUE TITLE
redirect to local html file

### ISSUE THREAD

**Issue by bgalvao** [AXeL-dev/distract-me-not#11]
I have a simple html page in the local filesystem that the extension tries to get over the web (naturally).
I think it'd be cool to let users make their own redirect page. Though, yes, I can set up a server to serve my custom redirect page, but that is too much work for a quick functionality imo.

**Comment by AXeL-dev** [comment]
Not a bad idea, i'll try to figure out how this can be achieved.

**Comment by bgalvao** [comment]
As a starter, Firefox at least allows you to access any local file by prefixing the url (file path) with `"file://"`.

When I tested, the following code always prefixes the `redirectUrl` with `"https://"`, no matter the value. It could be as simple as allowing the user to input `"file://"`.

```js
function redirectTab(tab) {
    //console.log(redirectUrl);
    if (isAccessible(tab) && redirectUrl != '' && !tab.url.startsWith(redirectUrl)) {
        if (! redirectUrl.startsWith("about:") && ! redirectUrl.startsWith("http://") &&  ! redirectUrl.startsWith("https://")) {
            redirectUrl = "https://" + redirectUrl;
        }
        disableEventHandlers();
        browser.tabs.update(tab.id, {
            url: redirectUrl,
            loadReplace: true
        }).then(function(tab) {
            enableEventHandlers();
        }, function(error) {
            enableEventHandlers();
        });
    }
}
```

(I may have time to write a PR, but I have yet to look up how to set up an environment to test the extension)

**Comment by AXeL-dev** [comment]
It's okay i'll implement it & test it since i'm working on the extension right now
