### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by therealeisbaer** [AXeL-dev/distract-me-not#13]
The blacklisting doesn't work anymore (9 May 2020). I can enter twitter.com e.g. but the tab isn't closed anymore. There is no green +, so the addon does recognize that it's blacklisted website.

**Comment by AXeL-dev** [comment]
I'll check that & get back to you.

By the way, have you try to switch the status off & then on to see if it has anything to do with the issue?

**Comment by therealeisbaer** [comment]
Switching the status off and on made no difference. I've deleted the addon and installed it again and it's working now.
