### ISSUE TITLE
Breaks keyboard shortcuts

### ISSUE THREAD

**Issue by svandragt** [AXeL-dev/distract-me-not#14]
Distract Me Not prevents the F6 and Ctrl/Cmd-L keyboard shortcuts from working. This prevents me from selecting the current URL and copying it (the shortcut focuses on the Address Bar).

### Test Case

- Enable the allowlist (with Display Error message mode)
- Visit a page not on the allowlist
- press CMD-L (mac) or equivalent shortcut to focus the address bar.

Expected: The current URL is selected in the address bar
Result: The URL is not selected and the address bar isn't focused.

### Context
I'm using this addon to prevent me using my 'web development' browser (Firefox Dev Edition) for regular browsing, with an allowlist for project related work. This works very well and helps me keep my privacy focused addons from blocking project assets.

Occasionally I would kick off a websearch for a problem and click through to another site, which then is blocked. So I wrote a Keyboard Maestro script to open the current site in another browser (https://gist.github.com/svandragt/3a15b79296654196c77c5cbfeea7be84 if you're interested). 

This doesn't currently work because of the above. Is this a bug or a feature? If the latter would you consider making it a preference?

BTW, thanks for making this plugin there are not many options for Firefox addons that work with an allow-list.

**Comment by AXeL-dev** [comment]
:thinking: needs investigation, i'll probably check it out this weekend. Thanks for reporting it!

**Comment by svandragt** [comment]
👍 Thanks, I've added a test scenario.

**Comment by spohngellert-o** [comment]
I can confirm I had this same issue, Firefox on Ubuntu 18.04

**Comment by AXeL-dev** [comment]
> Is this a bug or a feature? If the latter would you consider making it a preference?

In fact, it seems to be a feature, & honestly i do not remember well why did i introduce it to the error message overlay, so to avoid breaking things by mistake, i simply added an option under settings to re-enable that behavior & made it disabled by default.
