### ISSUE TITLE
Feature request: make the extension available on Firefox for Android

### ISSUE THREAD

**Issue by madiyarov** [AXeL-dev/distract-me-not#24]
Firefox for Android allows you to install extensions. It would be great if your extension would also be available on phones

**Comment by AXeL-dev** [comment]
Nice suggestion, still i'm thinking that the testing part would be important, so i'll try to find some time for that. If you're interested about helping on testing that would be great!

**Comment by madiyarov** [comment]
Would be happy to help

**Comment by AXeL-dev** [comment]
Well, the extension is fully compatible with firefox for android still for some "unknown" reasons it doesn't appear under the extensions compatible with Android on the addons store.
I'll try to contact the AMO support team, but if you're really in hurry, better consider using any other available alternatives.

**Comment by toropanov** [comment]
Thank you. If others are interested in installing this extension on their Android device, please follow these instructions - https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/ (not ad)

P.S Something strange with page width..
![Screenshot_20240830_181548_Firefox Beta](https://github.com/user-attachments/assets/c88d63e4-c6d3-4ef1-8e16-959e7ec40b80)
