### ISSUE TITLE
impossible to add 'localhost' to whitelist - Url is not valid

### ISSUE THREAD

**Issue by goffyara** [AXeL-dev/distract-me-not#28]
### Your environment
* Firefox 89.0

**Comment by AXeL-dev** [comment]
For which reason do you wanna block a local url :thinking: ?

**Comment by AXeL-dev** [comment]
The issue has been fixed, still not deployed yet (i'll try to release a new version in the next days), for now as a workaround:
- you can either export your whitelist to text file then add a new line with `localhost` string to the text file & re-import it.
- or you can switch to whitelist mode on the extension panel > then go to your localhost url (on the browser) & hit the green add button on the extension panel to add localhost url to the whitelist.

**Comment by AXeL-dev** [comment]
The issue has been fixed, still not deployed yet (i'll try to release a new version in the next days), for now as a workaround:
- you can either export your whitelist to text file then add a new line with `localhost` string to the text file & re-import it.
- or go to your localhost url (on the browser), then open the extension panel & switch to whitelist mode then hit the green add button to add localhost url to the whitelist.
