### ISSUE TITLE
What does it actually block?

### ISSUE THREAD

**Issue by rugk** [AXeL-dev/distract-me-not#3]
The doc/AMO description/Readme does not actually give me a lot of hints what it blocks…

I know this looks like WIP, but FYI: I personally then e.g. like it to first mark the add-on as "unstable version" on AMO.

----

BTW, you know me? I guess, because that style of the Readme is very familiar to me… :stuck_out_tongue_winking_eye: 

Okay, or possibly coincidence…?

**Comment by rugk** [comment]
Okay, possibly coincidence…

**Comment by AXeL-dev** [comment]
> The doc/AMO description/Readme does not actually give me a lot of hints what it blocks…

Well, it's just a simple website blocker using url detection to display an overlay on blocked websites, & i don't really have time right now to write a doc, so.. maybe later..

> I know this looks like WIP, but FYI: I personally then e.g. like it to first mark the add-on as "unstable version" on AMO.

You might be right, but unstable version should be for a beta/first release while the current version of the extension is working fine so why mark it as unstable :confused: 

> BTW, you know me? I guess, because that style of the Readme is very familiar to me… :stuck_out_tongue_winking_eye:

I just saw some of your extensions on github, BTW i'm using the emoji keyboard & i like it, great work :wink:

**Comment by rugk** [comment]
Ah great, so I was not wrong. (Because you certainly copied some parts of the Readme. – Which is totally, fine, I have to add. [Actually I even have a CC0 template for new add-ons.](https://github.com/TinyWebEx/AddonTemplate)

BTW: If you publicly link to the add-on stats, you should actually also make them public in AMO. Currently this leads to an error. :smile:

**Comment by AXeL-dev** [comment]
well, instead of "copying some parts of the Readme", i would like to say that i got inspired from it :laughing:

> BTW: If you publicly link to the add-on stats, you should actually also make them public in AMO. Currently this leads to an error. :smile:

Okay, i'm gonna fix this :+1:

**Comment by rugk** [comment]
Okay fine… I guess we can close this. :smiley:
