### ISSUE TITLE
Feature request: Have option to block only when it's not embedded

### ISSUE THREAD

**Issue by Huy-Ngo** [AXeL-dev/distract-me-not#32]
For example, I block YouTube to avoid procrastination, but in some cases, if a tutorial have an embedded youtube video it's ok to watch it.

(similar to #17 )

**Comment by AXeL-dev** [comment]
I just tested on this [example](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_youtubeiframe) & the video was blocked, so i think that maybe the embedded video has a different domain name from the one you're blocking. Can your share details about your blocked youtube urls + an example of embedded video that bypasses the blocking please?

**Comment by Huy-Ngo** [comment]
Sorry because I wasn't clear. I am suggesting a feature where you can choose not to block embedded videos or web pages in general.

**Comment by AXeL-dev** [comment]
> Sorry because I wasn't clear. I am suggesting a feature where you can choose not to block embedded videos or web pages in general.

Oops, it was me who didn't read the issue title correctly 😅.

Anyway, sure! i'll add this to the todo list! thanks for reporting it :smile: .

**Comment by AXeL-dev** [comment]
I think this has been fixed with the `combined` mode. I'm gonna close this issue for now.
