### ISSUE TITLE
Block sites but not their embeds

### ISSUE THREAD

**Issue by Sowee0** [AXeL-dev/distract-me-not#37]
Hello!
I love this extension and have been using it for quite some time. Let me first thank you for the scheduled blocking, it is perfect for my use case. 

Lately, however, I've been taking courses on EDX which use youtube embeds for it's videos. I have a rule for youtube blocking but found no way to add a blocking rule that'd exclude youtube.com/embed/. 

How can I go around this?
Thank you!

**Comment by Sowee0** [comment]
Duplicate of #32

**Comment by Sowee0** [comment]
Absolutely.
Setting the blocking mode to 'combined' and then adding *.youtube.com/embed/* seems to be working fine, blocking youtube but not youtube embeds in edX.

**Comment by AXeL-dev** [comment]
Alright, thank you for the confirmation!
