### ISSUE TITLE
Doesn't seem to work in LibreWolf

### ISSUE THREAD

**Issue by nonetrix** [AXeL-dev/distract-me-not#41]
Websites do not get redirected, maybe due to LibreWolf's hardening compared to base FireFox?

### Your environment
* 8.3.0
* v17.3.0
* ?
* LibreWolf LibreWolf 95.0

### Steps to reproduce
Install this extention on LibreWolf website blocking doesn't work does on Brave for example

### Expected behaviour
Website is redirected to block page

### Actual behaviour
Website is not redirected to block page

**Comment by nonetrix** [comment]
Also, I'm confused by your template, do you need the version of npn and node that or installed on my system, or the ones it was built with? There are no examples of how to get this information.

**Comment by AXeL-dev** [comment]
Hey,

I didn't hear of LibreWolf before, so i can't really figure out what's the matter here, still it might be related to differences between the extensions API of Firefox & LibreWolf, you should ask about that in their Forum maybe.

> Also, I'm confused by your template, do you need the version of npn and node that or installed on my system, or the ones it was built with? There are no examples of how to get this information.

I'm not sure if i get you well, but the project template is a [CRA](https://create-react-app.dev/) template, you need a recent version of node **on your system** to run it.

**Comment by nonetrix** [comment]
Seems to reduce finger printing the time is set wrong and I don't think theirs a way to disable it... Back to Waterfox or Ungoogled Chromium or Brave if I go full Brave shill
