### ISSUE TITLE
Minor Feature Request - Request count of List Items and last updated date

### ISSUE THREAD

**Issue by OttScott** [AXeL-dev/distract-me-not#57]
Problem Statement:
If using multiple browsers on multiple machines, I'd like to know that all my Black\White lists contain the same items, or failing that, the same number of items. Additionally, as I make changes to my lists, it would be helpful to know the last import date (or update date) of a given list so that I know the lists are at _least_ up to date with a certain source file date.

Requesting a Count of items contained within a Blac/White Keyword or URL list.
Also, requesting a last import/updated date of same lists.

Both features would allow user to determine if lists are properly imported or up to date with all browsers using this extension. Both date and count perhaps are overkill, but it would be helpful to know that I successfully imported my lists across all my browsers on all my machines.

Larger Feature of Cloud-Sync of lists would probably obviate this feature.

### Your environment

- 2.6.4
- Edge\Chrome newest

### Steps to reproduce

Open Extension Options page
Select Blacklist or Whitelist
Import a large (more items than fit in the window so scroll-bars appear) selection of URLs or keywords
Do the same on another browser and add more items
Compare the lists in both browsers. Are the lists the same?

**Comment by AXeL-dev** [comment]
As you said, i think that the [storage sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync) solution would be a better approach for that :thinking:.

Still adding the list count isn't a bad idea, but for the export date i think that you can simply know that from the export file creation date (still this would not resolve the case/need of an import date, for sure).

**Comment by OttScott** [comment]
Import Date isn't strictly a requirement, it just ties the data to a specific sync-state that could be tied to a given sync event. In the case of file-based sync, it's largely moot, but for Storage Sync you might be tracking the metadata anyway. I don't really think it's necessary to expose it to the user, but the current count of items in the list would be handy.

And please note, I do not consider this to be an important feature. If the UI of the Framework doesn't easily expose the list count or make it easy to display, I'd close as Won't-Fix.  But Storage Sync...  That'd be a useful thing...  :D

**Comment by AXeL-dev** [comment]
@ottscott both list count & import date are easy to implement, still the storage sync is something i never did before so it might require some time to be correctly implemented & tested.

I'll try to have a look on it this feature request this weekend, also do you have any suggestion for where to put the import date on the UI? maybe below the lists?

**Comment by OttScott** [comment]
@AXeL-dev Last Import Date might be replaced by Last Sync Date once implemented, but yeah, I think right below the lists is the best place. Maybe it should be Last Modified Date so any additions that were made would be known as well. Probably easier to implement anyway.

**Comment by AXeL-dev** [comment]
@OttScott what do you think of this?

![Peek 08-05-2022 14-47](https://user-images.githubusercontent.com/30635693/167299440-82c45037-1ef5-4823-8ac0-fa84cca9750c.gif)

**Comment by OttScott** [comment]
Amazing! Far better than I thought it'd be.
![image](https://user-images.githubusercontent.com/14189124/167303053-167d6d06-1ae3-4c6e-9572-ec8abfffc18a.png)

**Comment by AXeL-dev** [comment]
Deployed in version `2.6.5`, it may take some time until it becomes available on chrome & edge.
