### ISSUE TITLE
In Whitelist mode, cannot unblock the file:// URL scheme

### ISSUE THREAD

**Issue by dabreese00** [AXeL-dev/distract-me-not#6]
In Firefox, I am using Whitelist mode.  When I try to open a file:// URL scheme in the URL bar, e.g. `file:///home/username/file.html` (a Unix-like file path), it is blocked by Distract Me Not.  So far, so good.

The problem is, I can't seem to unblock the page.  Clicking the "+" button appears to work at first, in that the "+" button goes away, but then nothing else happens.  The page remains blocked, and no new entry appears in Distract Me Not's Whitelist on the settings  page.

Moreover, since a file:// URL lacks a domain name, doesn't really seem to fit Distract Me Not's whitelist-blacklist model.  Even if I was to manually type in a Whitelist entry for the page, I'm not sure what I'd type.

So currently, I can't view the page at all, while in Whitelist mode.  As a work-around, I just temporarily disable Distract Me Not.

Maybe it would be OK & an easy change to have Distract Me Not just never block any "file://" URLs?

By the way, thank you for this awesome plugin.

**Comment by AXeL-dev** [comment]
Bug confirmed, i'm working on a fix :wink:
