### ISSUE TITLE
FF 91.9.0esr - The extension can be disabled even when the password is set

### ISSUE THREAD

**Issue by wnxkiv85** [AXeL-dev/distract-me-not#60]
Version
2.6.5

FF 91.9.0esr (64-bit) from Debian stable repos

**Comment by AXeL-dev** [comment]
Hum :thinking: , Can you provide more details please? Like the websites you're trying to block? (you can send that to me on [my email](mailto:contact.axel.dev@gmail.com) if it's confidential).

Also a screenshot of the issue or a video might help me to better understand. Thank you.

**Comment by wnxkiv85** [comment]
same issue using 2.6.4, i´m using whitelist mode.

https://user-images.githubusercontent.com/46428150/167856411-e4e2842c-11a1-4db6-bbae-342de69d8de9.mp4

**Comment by AXeL-dev** [comment]
> same issue using 2.6.4, i´m using whitelist mode.
> 
> You may need to download the video to watch it properly.
> distractmetest.mp4

Do you have the domain name `youtube.com` on your whitelist? can you send me a screenshot of the whitelist settings please.

**Comment by wnxkiv85** [comment]
> 



> > same issue using 2.6.4, i´m using whitelist mode.
> > You may need to download the video to watch it properly.
> > distractmetest.mp4
> 
> Do you have the domain name `youtube.com` on your whitelist? can you send me a screenshot of the whitelist settings please. I might need to know what's on your blacklist settings as well. Thank you.

My friend, the blocking procedures are working flawlessly, the problem is that i can disable the entire extension without password by directly entering the add-ons and configuration FF menus.
![photo_2022-05-11_11-40-11](https://user-images.githubusercontent.com/46428150/167876929-9f300435-851f-491f-ac45-ae6494947178.jpg)

**Comment by AXeL-dev** [comment]
> My friend, the blocking procedures are working flawlessly, the problem is that i can disable the entire extension without password by directly entering the add-ons and configuration FF menus. ![photo_2022-05-11_11-40-11](https://user-images.githubusercontent.com/46428150/167876929-9f300435-851f-491f-ac45-ae6494947178.jpg)

This is known issue, & firefox doesn't provide a way to disallow the user from disabling an extension, you should open an issue in the [mozilla addons repo](https://github.com/mozilla/addons)  for that.

Additionnaly, even your password can be bypassed easily (check this https://github.com/AXeL-dev/distract-me-not/issues/27#issuecomment-854942738).

**Comment by wnxkiv85** [comment]
this addon [foxfilter](https://www.foxfilter.com/) can do it.

**Comment by AXeL-dev** [comment]
> this addon [foxfilter](https://www.foxfilter.com/) can do it.

They probably use a hacky way for that, since from what i know there is no API that let you do this.

Nonetheless, i'll try to have a look on their code source if it's open source & check how it is implemented.

**Comment by wnxkiv85** [comment]
I am currently using the following policies.json file as a workaround.

`{
  "policies": {
    "ExtensionSettings": {
        "uBlock0@raymondhill.net": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi"
      }, 
        "{5f884915-160e-4276-a216-770a753a3abe}": {
        "installation_mode": "force_installed",
        "install_url": "https://addons.mozilla.org/firefox/downloads/latest/distract-me-not/latest.xpi"
      },
    "Extensions": {
      "Locked":  ["{5f884915-160e-4276-a216-770a753a3abe}"]
    },     
    }
  }
}`

**Comment by AXeL-dev** [comment]
Fixed in version `2.7.0`, you still need to enable the following option in the settings:

![Capture d'écran Deepin_zone de sélection _20220514193447](https://user-images.githubusercontent.com/30635693/168496456-3ccf0be7-5cc8-4a31-8f04-83afc0207967.png)
