### ISSUE TITLE
Feature Request: Allow iframes and embeds from blacklisted sites to load on whitelisted sites

### ISSUE THREAD

**Issue by JulianWebb** [AXeL-dev/distract-me-not#63]
Hello AXeL, thank you for your work on this. I recently installed it as I found I was wasting far too much time on sites that were distracting.

I would like to request that when a blacklisted site, e.g. YouTube, is within an iframe or embed on a whitelisted site, e.g. an online learning site, that the plugin allows it to load and be accessed by the user.

I ask because my current course is mostly videos hosted on YouTube and embed into a Moodle install using iframes, which means I either need to remove YouTube from the blocklist while I work on it, or leave it off and I am not sure I have the willpower to stop myself from getting distracted in either case.

I don't know how difficult this would be, I haven't looked into how the plugin works, but if it's possible I would love to see it.

**Comment by JulianWebb** [comment]
My apologizes, I didn't see those, you are correct that they have a working solution in regards to Youtube Embeds.

If in the future someone needs other Embeds to work, I think adding a setting around enabling or disabling `sub_frame` [here](https://github.com/AXeL-dev/distract-me-not/blob/88da636edd6676ace1526f99f403f1fb74734fe0/src/components/Background/index.jsx#L868) might be the solution, but that's more effort than is needed right now.

I would recommend adding an FAQ to the README and/or In-Extension Web App for questions like this, but that'd be for a different feature request.

**Comment by AXeL-dev** [comment]
@JulianWebb I added an option to block only main frames on the blocking settings, it will be available on the next release!
