### ISSUE TITLE
DMN not Blocking when Browser first starts (even though Block is enabled)

### ISSUE THREAD

**Issue by OttScott** [AXeL-dev/distract-me-not#65]
When Edge loads from a closed session (restoring all my tabs), Distract-Me-Not is enabled and Active. Clicking the icon shows password prompt and, once supplied, indicates blocking is active in Combined mode. Blocking is not working, however, until I disable blocking and re-enable it.

### Your environment
- version of the extension
Version 2.7.1 
- which browser and its version
Win10 Edge vCurr = 'Version 103.0.1264.44 (Official build) (64-bit)'

### Steps to reproduce
-Close edge with Tabs open and set to restore tabs on open (Unsure if necessary. Have not tested other variations)
-Reopen Edge (Which restores saved tabs and extension states)
-Open a New Tab and navigate to a location that should be blocked -> Notice it is not blocked
-Ensure Extension is Enabled and Status is Active in Combined Mode  (Supplying password as needed)
![image](https://user-images.githubusercontent.com/14189124/177809731-b60a6562-d4ee-4c98-986b-559b6e793ee5.png)
-Open DMN Settings (Supplying password as needed)
-Notice Active and Blocking is in Combined Mode
![image](https://user-images.githubusercontent.com/14189124/177809901-d8a3c437-4ac3-4fad-b0b8-a15b2093693c.png)

-Verify Tab destination _should_ be blocked by verifying Blacklist
![image](https://user-images.githubusercontent.com/14189124/177810021-79534e52-b991-4d05-b4ea-6908e2d47371.png)

-Disable Blocking (And Save)
![image](https://user-images.githubusercontent.com/14189124/177810096-965de494-dc8f-475f-9eeb-4efe14de8f28.png)

-Re-enable Blocking (And Save) -> Notice existing working tab suddenly becomes blocked
![image](https://user-images.githubusercontent.com/14189124/177810563-258b0fb9-8f5b-471a-adca-19ceb8174e81.png)

### Expected behaviour
On load, the extension should verify blocking status and ensure every tab is blocked as appropriate

### Actual behaviour
On load, tabs that should be blocked, as well as new tabs that should be blocked, are not blocked until blocking is turned off and back on.

**Comment by AXeL-dev** [comment]
Tested on Edge `Version 103.0.1264.51` (Linux version) & i couldn't reproduce the bug, i used the combined mode + (tried with & without a password) & the blocking works fine even after many restarts & or enabling/disabling the extension.

Can you provide more details about how was you able to load the websites from an old session?

**Comment by AXeL-dev** [comment]
Hey @OttScott, i know that you didn't check back yet, still i just wanted to add something: can you please send me your settings (all the settings if possible), because i'm quite sure that there is a specific case where the issue happens still i can't yet reproduce it. Thanks!

**Comment by OttScott** [comment]
Sorry. Yes. I’ve been on vacation for a bit here. Will check into this when
I get back home.

**Comment by OttScott** [comment]
OK, looking into it now, I cannot find a way to export my config. Do you want my Black/Whitelists posted here? What about other settings? Is there a way to export it into CSV or something?

**Comment by AXeL-dev** [comment]
@OttScott there is no way to export the whole settings for now, so if you can send me screenshots of each setting tab + your blacklist/whitelist on my [email](mailto:contact.axel.dev@gmail.com), that would be helpful (sorry for the inconvenience).

**Comment by AXeL-dev** [comment]
@OttScott I was able to reproduce the issue using your config files (thanks!), i'll investigate more & work on a fix for the issue.

**Comment by AXeL-dev** [comment]
@OttScott i've found the origin of the error, it was mainly related to the keywords list which was not correctly handled when the extension gets loaded on the browser start. The fix would be available on the next release!

Additionally, i've added buttons to export/import all the settings under the `Miscellaneous` tab.
