### ISSUE TITLE
Feature Request: Add Report an Issue and Timer to Extension Password dialog

### ISSUE THREAD

**Issue by OttScott** [AXeL-dev/distract-me-not#66]
Clicking the Extension to enable Timer Mode or Report an Issue with Password Enabled requires entering Password before you can do either

### Your environment

- version of the extension
2.7.1
- which browser and its version
Edge vCurr

### Steps to reproduce
-Enable Password for extension option management
-Click Distract-Me-Not to Open the Dialog -> Notice you cannot Enable Timer or Report an Issue
-Enter your Password -> Notice you can now do either

### Expected behaviour
Report an Issue or Enable the Timer without entering a password (Disable Timer should still require password)

### Actual behaviour
Cannot do either without entering a password

**Comment by AXeL-dev** [comment]
For the timer that's already possible:

![Capture d'écran Deepin_zone de sélection _20220708104534](https://user-images.githubusercontent.com/30635693/177965849-27134236-7794-45b8-971d-27727460e4d2.png)

You just have to enable it from the password settings:

![Capture d'écran Deepin_zone de sélection _20220708104741](https://user-images.githubusercontent.com/30635693/177965914-d45c5fcc-56dc-43d3-9b18-37df1368b9c9.png)

For the report issue button it's not yet implemented on the password dialog, so let's keep this issue open until it gets added.

**Comment by AXeL-dev** [comment]
@OttScott Fixed! will be available on the next release!
