### ISSUE TITLE
Block Google searches

### ISSUE THREAD

**Issue by tcdaly** [AXeL-dev/distract-me-not#90]
Is there any way of blocking Google searches for a specific keyword?
i.e. block the URL beginning `https://www.google.com/search?q=foo`, where `foo` is the search term to be blocked?

### Your environment

- version of the extension 2.0.8
- which browser and its version Firefox v109.0

**Comment by AXeL-dev** [comment]
Hello,

Yes, simply add the url `https://www.google.com/search?q=foo` to the urls blacklist as so:

![Screen Capture_select-area_20230209225552](https://user-images.githubusercontent.com/30635693/217948375-926fe149-eec3-4c2c-8bd9-38baf559c230.jpg)

Furthermore, you can add an asterisk `*` at the end of the url to block any keyword starting with `foo` => `https://www.google.com/search?q=foo*`.

**Comment by tcdaly** [comment]
Thank you for your reply.

Unfortunately that doesn't work.  Google puts a lot of other text in the URL following the search term, so I tried adding a wildcard * to account for this, i.e. 

https://www.google.com/search?q=foo*

But this doesn't help.

However, I tried adding the search term as a keyword under the 'keywords' tab, and that does work, i.e.

/foo/i
