### ISSUE TITLE
My keywords are always invalid

### ISSUE THREAD

**Issue by Anveron** [AXeL-dev/distract-me-not#94]
I've tried to put into whitelist keywords the keyword list, so it would allow me to visit youtube playlists, but it says the keyword is not valid. I've tried to put in the examples (foo, bar) and it is still not valid. I feel like I must be missing something.

I use Firefox 112.0.2 and the addons version is 2.8.0.

**Comment by AXeL-dev** [comment]
Hello, sorry for the late answer, can you provide more details like screenshots or maybe a video demonstrating the issue.
