### ISSUE TITLE
Option to enable Blob URLs to be added into Blacklist.

### ISSUE THREAD

**Issue by RobConner** [AXeL-dev/distract-me-not#99]
Describe your issue here.

Version 2.8.0
Firefox 115.8.0.esr

### Steps to reproduce

Whenever I try to add a Blob URL (More info here -> https://stackoverflow.com/questions/30864573/what-is-a-blob-url-and-why-it-is-used) into Distract-Me-Not's Blacklist, I encounter the "This is not a valid URL." error MessageBox.

### Expected behaviour

I would like for your extension to please enable the addition of Blob URLs (eg. - blob:null/7b2e7a34-8573-4c16-a3bb-8fb89577e5b4) as recently, more hackers are using such URLs in infected ads to try to inject files with malware into my HDD via my browser.

### Actual behaviour

Whenever I try to add a Blob URL into Distract-Me-Not's Blacklist, I encounter the "This is not a valid URL." error MessageBox (Understandable since a Blob URL is not the same as an actual HTTP URL).

**Comment by AXeL-dev** [comment]
This was implemented on release `2.8.1`, i will close the issue, please re-open it in case you still reproduce it.
